
import { GoogleGenAI, Modality } from "@google/genai";
import { CanvasNode } from '../types';
import { getImage } from './dbService';
import { blobToBase64 } from "../utils/canvasUtils";

if (!process.env.API_KEY) {
  console.warn("API_KEY environment variable not set. Please set it to use the Gemini API.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

function base64ToPart(base64: string) {
    const match = base64.match(/^data:(image\/\w+);base64,(.*)$/);
    if (!match) {
        return null;
    }
    const [_, mimeType, data] = match;
    return {
        inlineData: {
            mimeType,
            data
        }
    };
}


export const generateImageFromNodes = async (nodes: CanvasNode[]): Promise<Blob> => {
  const textParts = nodes
    .filter(node => node.type === 'text')
    .map(node => ({ text: node.content }));

  const imageNodeParts = await Promise.all(nodes
    .filter(node => node.type === 'image')
    .map(async (node) => {
      try {
        const blob = await getImage(node.content);
        if (!blob) return null;
        const base64 = await blobToBase64(blob);
        return base64ToPart(base64);
      } catch (e) {
        console.error(`Failed to load image ${node.id} from DB`, e);
        return null;
      }
    })
  );

  const imageParts = imageNodeParts.filter(part => part !== null).map(part => part!);

  if (textParts.length === 0 && imageParts.length === 0) {
    throw new Error("Cannot generate image from empty selection.");
  }

  const promptParts = [...imageParts, ...textParts];
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [{
        parts: promptParts,
      }],
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const mimeType = part.inlineData.mimeType;
        const res = await fetch(`data:${mimeType};base64,${base64ImageBytes}`);
        return await res.blob();
      }
    }
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    throw new Error("Failed to generate image. Check the console for details.");
  }
};
